### ISSUE TITLE
Not being able to run for large number of sequences (>10000 sequences)

### ISSUE THREAD

**Issue by Dfvandenberg** [qianfeng2/detREC_program#2]
Hi,

I am trying to make the "Mosaic Program to Detect Partial Alignments From Large Unaligned Sequences" work, but I am pretty sure that all the paths are incorrect in all the files and are directed towards your account etc (especially the moaic_est_par.sh scripts.
When I try to run estimate_transition_probs_frn_viterbi_qian.py, it gives the following error: Typerror: 'NonType' object has no attribute '__getitem__'. This code is also in python2 while the rest of your code is python3, which is confusing.

I have 16000 proteins so this step is pretty necessary, if I use the normal route, it kills itself at the "Computing alignment paths for each sequence" step.

Can you help me with running your tool?

With kind regards,
Daan

**Comment by qianfeng2** [comment]
Hi Daan,

Thanks very much for your query and trying to use mosaic tool. 

Firstly, as I mentioned in the run example of [(Readme),](https://github.com/qianfeng2/detREC_program/tree/master/Empirical_script), I used the estimate_transition_probs_frm_viterbi.py, instead of estimate_transition_probs_frn_viterbi_qian.py. Therefore I did not upload correct version and I have modified this. Sorry about that! Please give it a try again. Also, reading through Readme would be pretty helpful for you.

Secondly, I understand it is quite confusing this script was written by python 2. This script actually comes from peer's work, instead of ours. I am happy to rewrite into python 3 after getting related person's permission.

Finally, it is not recommended to run the normal route for your 16000 proteins, as this will cost resources (memory and time), my experience tells if it kills itself, most probable reason is there lack enough memory when running mosaic program for current data size.

It's great you try to run mosaic program for your dataset, even though this amazing pipeline is not our work. Our work is to propose an algorithm to detect recombinants from existing the partial alignments. I am happy to receive any questions/feedback, if any question please contact:  fengq2@student.unimelb.edu.au

Regards,
Qian
